import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { getActiveProducts, type Product } from '../../src/services/catalog';
type Cart = Record<string, number>;
export default function OrderScreen() {
 const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<Cart>({}); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
 const loadProducts=useCallback(async()=>{try{setError(null);setProducts(await getActiveProducts());}catch{setError('No pudimos cargar el menú. Intenta de nuevo.');}finally{setLoading(false);setRefreshing(false);}},[]); useEffect(()=>{void loadProducts();},[loadProducts]);
 const changeQuantity=useCallback((id:string,delta:number)=>setCart(current=>{const next=Math.max(0,(current[id]??0)+delta);if(!next){const {[id]:_removed,...rest}=current;return rest;}return {...current,[id]:next};}),[]);
 const selected=useMemo(()=>products.flatMap(p=>{const quantity=cart[p.id]??0;return quantity?[{name:p.name,quantity,price:Number(p.price)}]:[];}),[cart,products]);
 const summary=useMemo(()=>selected.reduce((r,i)=>({items:r.items+i.quantity,total:r.total+i.quantity*i.price}),{items:0,total:0}),[selected]);
 const checkout=()=>router.push({pathname:'/checkout',params:{items:JSON.stringify(selected)}});
 if(loading)return <View style={styles.centered}><ActivityIndicator size="large"/><Text style={styles.muted}>Cargando menú…</Text></View>;
 return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>Pedir</Text><Text style={styles.subtitle}>Menú disponible</Text></View>{error?<View style={styles.messageBox}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>void loadProducts()} style={styles.retryButton}><Text style={styles.retryText}>Reintentar</Text></Pressable></View>:null}<FlatList data={products} keyExtractor={i=>i.id} contentContainerStyle={products.length?styles.list:styles.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void loadProducts();}}/>} ListEmptyComponent={<Text style={styles.muted}>Todavía no hay productos activos publicados.</Text>} renderItem={({item})=>{const quantity=cart[item.id]??0;return <View style={styles.card}>{item.image_url?<Image source={{uri:item.image_url}} style={styles.image}/>:null}<View style={styles.productBody}><Text style={styles.productName}>{item.name}</Text>{item.description?<Text style={styles.description}>{item.description}</Text>:null}<Text style={styles.price}>C$ {Number(item.price).toFixed(2)}</Text><View style={styles.quantityRow}><Pressable disabled={!quantity} onPress={()=>changeQuantity(item.id,-1)} style={[styles.quantityButton,!quantity&&styles.disabled]}><Text style={styles.quantityButtonText}>−</Text></Pressable><Text style={styles.quantity}>{quantity}</Text><Pressable onPress={()=>changeQuantity(item.id,1)} style={styles.quantityButton}><Text style={styles.quantityButtonText}>+</Text></Pressable></View></View></View>;}}/>{summary.items>0?<Pressable accessibilityRole="button" onPress={checkout} style={styles.cartBar}><View><Text style={styles.cartItems}>{summary.items} producto{summary.items===1?'':'s'}</Text><Text style={styles.cartTotal}>C$ {summary.total.toFixed(2)}</Text></View><Text style={styles.cartAction}>Continuar →</Text></Pressable>:null}</View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#fff'},centered:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:24},header:{paddingHorizontal:20,paddingTop:18,paddingBottom:10},title:{fontSize:28,fontWeight:'800'},subtitle:{marginTop:3,fontSize:14,color:'#666'},list:{padding:16,gap:14,paddingBottom:120},emptyList:{flexGrow:1,alignItems:'center',justifyContent:'center',padding:24},card:{borderWidth:1,borderColor:'#e8e8e8',borderRadius:18,overflow:'hidden',backgroundColor:'#fff'},image:{width:'100%',height:190,backgroundColor:'#f3f3f3'},productBody:{padding:16},productName:{fontSize:19,fontWeight:'800'},description:{marginTop:6,color:'#666',lineHeight:20},price:{marginTop:10,fontSize:18,fontWeight:'800'},quantityRow:{flexDirection:'row',alignItems:'center',gap:14,marginTop:14},quantityButton:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:'#111'},quantityButtonText:{color:'#fff',fontSize:24,fontWeight:'700'},quantity:{minWidth:24,textAlign:'center',fontSize:18,fontWeight:'700'},disabled:{opacity:.25},muted:{color:'#666',textAlign:'center'},messageBox:{marginHorizontal:16,padding:14,borderRadius:12,backgroundColor:'#f7f7f7'},error:{color:'#8a1c1c'},retryButton:{alignSelf:'flex-start',marginTop:10,padding:8,borderRadius:8,backgroundColor:'#111'},retryText:{color:'#fff',fontWeight:'700'},cartBar:{position:'absolute',left:14,right:14,bottom:12,borderRadius:16,padding:16,backgroundColor:'#111',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cartItems:{color:'#fff',fontSize:13},cartTotal:{color:'#fff',fontSize:20,fontWeight:'800'},cartAction:{color:'#fff',fontWeight:'800'}});
